// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nlfhvlnmuhkxzgherccj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5sZmh2bG5tdWhreHpnaGVyY2NqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkyNzk5NzEsImV4cCI6MjA2NDg1NTk3MX0.56xzDUqEc9MYcjiNin59spQ7eoWft9HvYYvGvgnfMlI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);